/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var configuration = require('../lib/configuration');
var environments = require('../lib/Environments');

var testConfiguration = {
    ASSERT_PRECISION: 0.01,
    TEST_TIMEOUT: 30000
};

module.exports = testConfiguration;
