/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var assert = require('chai').assert;
var TestHelper = require('../TestHelper');
var APIHelper = require('../../lib/APIHelper');
var testerlib = require('../../lib');
var testConfiguration = require('../TestBootstrap');

var controller = testerlib.SimpleCalculatorController;
 
var OperationTypeEnum = testerlib.OperationTypeEnum;

describe('SimpleCalculatorController Tests', function() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Check if multiplication works
     */ 
    it('should testMultiply response', function(done) {
        // Parameters for the API call
        var input = [];
        input["operation"] = new OperationTypeEnum(MULTIPLY);
        input["x"] = 4;
        input["y"] = 5;

        controller.getCalculate(input, function(error, response, context) {
            // Test response code
            assert.equal(200, context.response.statusCode);
            assert.isNotNull(response);
 
            //not an array, do simple check
            assert.equal(20, response);
            done();
        });
    });

});
