/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

var OperationTypeEnum = {

    //Represents the sum operator
    SUM : "SUM",

    //Represents the subtract operator
    SUBTRACT : "SUBTRACT",

    //Represents the multiply operator
    MULTIPLY : "MULTIPLY",

    //Represents the divide operator
    DIVIDE : "DIVIDE"

};

module.exports = OperationTypeEnum;
