/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
var servers = require('./Servers');
var environments = require('./Environments');
var apiHelper = require('./APIHelper');

var environmentsMap = [];
var e = environments;
var s = servers;

environmentsMap[e.PRODUCTION] = [];

environmentsMap[e.PRODUCTION][s.MDEFAULT] = "http://examples-apimatic-io-{runscope-bucket-key}.runscope.net/apps/calculator";

var Configuration = {
    //The base Uri for API calls
    BASEURI : "http://examples-apimatic-io-{0}.runscope.net/apps/calculator",

    //get your bucket id from runscope.com
    //TODO: Replace the RunscopeBucketKey with an appropriate value
    runscopeBucketKey : "TODO: Replace",

    //The OAuth 2.0 access token to be set before API calls
    //TODO: Replace the OAuthAccessToken with an appropriate value
    oAuthAccessToken : "TODO: Replace",

    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.PRODUCTION,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        var url = environmentsMap[this.currentEnvironment][server || servers.MDEFAULT];
        var urlParams = {
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
