/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

var Environments = {

    //TODO: Write general description for this element
    PRODUCTION : "production"

};

module.exports = Environments;
