/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

var logger = require('winston');

var BaseController = {

     /**
     * Helper function to print error logging messages
     * @param	{number}	code	The error code which needs to be logged
     */
    printErrorLog(code, endpName) {
        logger.error("Status code: " + code + " received for " + endpName + ".");
    },

    /**
     * Global error handling
     * @param	{HttpContext}	context			HttpContext containing request and response objects
	 * @param	{string}		endpName		Name of the endpoint called
     * @return	{function}		callback		Callback function in the form of function(error, response, context)
     */
    validateResponse(context, endpName) {
        var errorObj = {
            errorMessage: "",
            errorCode: "",
            errorResponse: context.response.body
        };
        var returnObj = {
            error: errorObj,
            response: null,
            context: context
        };

        BaseController.printErrorLog(context.response.statusCode, endpName);

        returnObj.error.errorMessage = "HTTP Response Not OK";
        returnObj.error.errorCode = context.response.statusCode;

        return returnObj;
    }
};

module.exports = BaseController;
